/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Enquiry = IDL.Record({
  'name' : IDL.Text,
  'propertyId' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const Property = IDL.Record({
  'id' : IDL.Text,
  'pricePerNight' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'ecoFeatures' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
  'maxGuests' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addProperty' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Nat,
        IDL.Nat,
      ],
      [],
      [],
    ),
  'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
  'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getProperty' : IDL.Func([IDL.Text], [Property], ['query']),
  'getSeedProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'reset' : IDL.Func([], [], []),
  'submitEnquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Enquiry = IDL.Record({
    'name' : IDL.Text,
    'propertyId' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const Property = IDL.Record({
    'id' : IDL.Text,
    'pricePerNight' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'ecoFeatures' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
    'maxGuests' : IDL.Nat,
  });
  
  return IDL.Service({
    'addProperty' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Nat,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
    'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getProperty' : IDL.Func([IDL.Text], [Property], ['query']),
    'getSeedProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'reset' : IDL.Func([], [], []),
    'submitEnquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };